import { ValueProvider } from '@/context/ValueContext'
import './globals.css'
import { ChakraProviders } from './providers'
import { Wrapper } from '@/components/Wrapper'
import { AuthProvider } from '@/components/AuthProvider'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ValueProvider>
            <ChakraProviders>
              <Wrapper>
                {children}
              </Wrapper>
            </ChakraProviders>
          </ValueProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
